### ISSUE TITLE
Problem using the repository as a standalone module (directory errors with PyCharm)

### ISSUE THREAD

**Issue by huyanhh** [siversalih/pyChrome#3]
In PyCharm, I'm setting the working directory to my project folder, and PyChrome is a folder within that folder. Unfortunately, I'm getting errors like this when I try to import PyChrome:

`CRITICAL:root:Path .../project_folder/src does not exist`

To work around this, I have to change some lines of code in `pyChrome.py` like so:

`curr_dir = "{}".format(os.getcwd())` to `curr_dir = "{}/pyChrome".format(os.getcwd())

However, I'm still having problems such as this one:

`CRITICAL:root:config.json is not in /project_folder` because the config.json is actually in the pyChrome folder instead.

I'm not too experienced with path libraries in Python, so it would take me a while to fix it. Otherwise, I would have to set my entire working directory setting in PyCharm to the pyChrome folder, but then if I have other Python files outside that folder and I'm trying to access the main directory for file reads for example, the directories get messed up.

When I try to run my program on the command line, I get this error:
```
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from pyChrome import PyChrome
ImportError: cannot import name 'PyChrome'
```

which leads me to believe that it is rather difficult to create files outside of that folder

Possible solutions:

-Turn the repository into a pip package and make it completely independent
-Fix the directory calls and specify in the docs how to access the module via different mediums

**Comment by siversalih** [comment]
Its correct, if you try to run pyChrome all the files need to be placed inside that folder as how you checkout the project. If you import pyChrome into separate project then your main.py need to be placed inside that folder.

As for solution, this is not an issue as long you don't make your project complex. And in that case, you need to tweak all the folder pointers such as curr_dir and src_dir in pyChrome.py, as you have, to be able to create files outside of that.

However, I like the idea of making it into pip package to actually be able to import pyChrome in any directory such as some of other python module (i.e urlib). Although, the project is not there yet, it's still missing some APIs and not tested with some types of Web element and application.
